# Generated by Django 3.2.5 on 2021-07-24 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('color', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moov_app.floorplan')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotated', models.IntegerField(default=1)),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moov_app.floorplan')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moov_app.furniture')),
            ],
        ),
        migrations.AddField(
            model_name='floorplan',
            name='furnitures',
            field=models.ManyToManyField(through='moov_app.LinkedFurniture', to='moov_app.Furniture'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
