# Generated by Django 3.2.5 on 2021-07-22 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moov_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='user_id',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
