# Generated by Django 3.2.5 on 2021-07-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moov_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='name',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
