# Generated by Django 3.2.5 on 2021-07-29 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moov_app', '0002_floorplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='color',
            field=models.CharField(choices=[('G', 'Grey'), ('B', 'Brown'), ('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow')], default='G', max_length=1),
        ),
        migrations.CreateModel(
            name='CurrentFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentfloorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moov_app.floorplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
