# Generated by Django 3.2.5 on 2021-07-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moov_app', '0003_auto_20210729_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='color',
            field=models.CharField(choices=[('Grey', 'Grey'), ('Brown', 'Brown'), ('Red', 'Red'), ('Orange', 'Orange'), ('Beige', 'Beige')], default='Grey', max_length=10),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='width',
            field=models.FloatField(),
        ),
    ]
