# Generated by Django 3.2.5 on 2021-07-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moov_app', '0004_auto_20210729_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='color',
            field=models.CharField(choices=[('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Red', 'Red'), ('Orange', 'Orange'), ('Black', 'Black')], default='Yellow', max_length=10),
        ),
    ]
